version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: bnb-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: bnb-creator-platform
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: bnb-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/bnb-creator-platform
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: bnb-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongodb_data:

